# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6daebd5f52a48529915bc3aba3552d1bb082d3afea1ead1d675c69ca904af9bfcaceadf83992f969d0b446fd072584217370d0b8be48d8dedf53c2aa879af95

test:
  secret_key_base: ae27d209cfa3ae18cbaf0976f50ae849abe19f7d1a3c396eb7752b62eb1caa14338660ceabce0b69b130497bd492eff5ecfa7933d70061aa4f74503717e0514c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
